name: azure_speech_recognition_flutter_example
description: "Demonstrates how to use the azure_speech_recognition_flutter plugin."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^12.0.0+1
  flutter_dotenv: ^5.2.1
  azure_speech_recognition_flutter:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
