name: azure_speech_recognition_flutter
description: "Azure Speech Recognition for Flutter"
version: 1.0.2
homepage: https://github.com/ARASHz4/azure_speech_recognition_flutter

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.arashz4.azure_speech_recognition_flutter
        pluginClass: AzureSpeechRecognitionFlutterPlugin
      ios:
        pluginClass: AzureSpeechRecognitionFlutterPlugin
